### ISSUE TITLE
Error with loading the saved model

### ISSUE THREAD

**Issue by KwinBobby** [souravs17031999/FLOWER-CLASSIFIER-WEBAPP#1]
I installed all the packages in the requirements.txt
However, when I run the following commands after reaching the directory with the files and folders:

`set FLASK_APP=flower.py
python -m flask run`

I get the following error:

`(base) C:\Users\kwinb\Downloads\FLOWER-CLASSIFIER-WEBAPP-master>python -mflask run
 Serving Flask app "flower.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "C:\Users\kwinb\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\kwinb\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\flask\__main__.py", line 14, in <module>
    main(as_module=True)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\flask\cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\flask\cli.py", line 293, in __init__
    self._load_unlocked()
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\flask\cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\flask\cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\flask\cli.py", line 235, in locate_app
    __import__(module_name)
  File "C:\Users\kwinb\Downloads\FLOWER-CLASSIFIER-WEBAPP-master\flower.py", line 4, in <module>
    from inference import get_flower_name
  File "C:\Users\kwinb\Downloads\FLOWER-CLASSIFIER-WEBAPP-master\inference.py", line 11, in <module>
    model = get_model()
  File "C:\Users\kwinb\Downloads\FLOWER-CLASSIFIER-WEBAPP-master\commons.py", line 13, in get_model
model.load_state_dict(torch.load(checkpoint_path,map_location='cpu'),strict=False)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\torch\serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\kwinb\Anaconda3\lib\site-packages\torch\serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.`

How do I solve this?

**Comment by souravs17031999** [comment]
Files were not properly loaded. Try again.
